---
galaxy_info:
  author: MasterChief Platform
  description: Common base configuration for all Linux servers
  company: Balestrine DevOps
  license: MIT
  min_ansible_version: 2.14
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - system
    - common
    - base

dependencies: []
